### ISSUE TITLE
Typo in mutation updateProjectV2ItemFieldValue query

### ISSUE THREAD

**Issue by Pierre-Geffriaud-Wiztivi** [Fmanuel809/github-project-automation-v2#1]
Hi
Awaiting for https://github.com/github/roadmap/issues/281 to be implemented by Github teams, I was looking at your great work. It could help me making my Project v2 more automatic.

However, it seems there's a issue on the mutation query when trying to update a "selectOption" value.

Here is my workflow file calling your action:
```yaml
-   uses: Fmanuel809/github-project-automation-v2@0.8.2
    with:
        project: xxx
        column: In Progress
        repo-token: ${{ secrets.GHPROJECT_TOKEN }}
```

The graphql query sent:
```
mutation {
    updateProjectV2ItemFieldValue( input: {
        projectId: "xxx",
        itemId: "yyy",
        fieldId: "zzz",
        values: {
            singleSelectOptionId: "foo"
        }
    }) 
    {
        projectV2Item {
            id
        }
    } 
}
```

And the error:
> **Error:** Argument 'value' on InputObject 'UpdateProjectV2ItemFieldValueInput' is required. Expected type ProjectV2FieldValue!

By updating `values` by `value` in the graphql query, it seems the request then works properly.
As written in the Github api documentation: https://docs.github.com/en/graphql/reference/input-objects#updateprojectv2itemfieldvalueinput
Do you think you can fix it ?

Thanks
